FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY data/    data/
COPY producer/ producer/

CMD ["python", "producer/train_producer.py"]
